import AxeBuilder from "@axe-core/playwright"
import { expect, test, type Page } from "@playwright/test"

async function enter(page: Page) {
  await page.emulateMedia({ reducedMotion: "reduce" })
  await page.clock.install({ time: new Date("2026-09-11T08:00:00Z") })
  await page.clock.pauseAt(new Date("2026-09-11T09:00:00Z"))
  await page.goto("/agentix-prototype")
  await expect(page.getByRole("heading", { name: /decisions\. Everything else is moving\./ })).toBeVisible()
}
const ticks = (page: Page, n: number) => page.clock.runFor(n * 4000)
async function open(page: Page, agent: string) {
  if (agent === "Employee onboarding agent") {
    await page.getByRole("button", { name: "New agent", exact: true }).click()
    await page.getByLabel("Describe the responsibility").fill("Coordinate employee onboarding")
    await page.getByRole("button", { name: "Prepare agent" }).click()
    return
  }
  await page.locator(".aop-agent-line").filter({ hasText: agent }).click()
}
const caseRow = (page: Page, id: string) => page.locator(".aop-run-row").filter({ hasText: id })
const close = (page: Page) => page.getByRole("button", { name: "Close details" }).click()
async function send(page: Page, text: string) {
  await page.locator("#aop-message").fill(text)
  await page.getByRole("button", { name: "Send instruction" }).click()
}
async function repairMapping(page: Page) {
  await page.getByRole("button", { name: "Confirm mapping" }).click()
  await page.getByLabel("London analyst → approved access package").selectOption("london-standard")
  await page.getByRole("button", { name: "Recheck readiness" }).click()
  await expect(page.getByText("Validating mapping, operation coverage and read-back…")).toBeVisible()
  await ticks(page, 1)
}

test("operations portfolio keeps decisions, work, activity, connections and steering in context", async ({ page }) => {
  await enter(page)
  await expect(page.getByRole("navigation", { name: "Agentix views" }).getByRole("button")).toHaveCount(5)
  await expect(page.locator(".aop-agent-line")).toHaveCount(3)
  await expect(page.getByRole("textbox", { name: "Steer Agentix" })).toBeVisible()
  await expect(page.locator("#aop-message")).toHaveCount(0)
  const views = page.getByRole("navigation", { name: "Agentix views" })
  await views.getByRole("button", { name: "Work", exact: true }).click()
  await expect(page.getByRole("heading", { name: "Work" })).toBeVisible()
  await views.getByRole("button", { name: /Approvals/ }).click()
  await expect(page.getByRole("button", { name: "Review" }).first()).toBeVisible()
  await views.getByRole("button", { name: "Today", exact: true }).click()
  await open(page, "Invoice operations agent")
  await expect(page.locator(".aop-run-row")).toHaveCount(5)
  await expect(caseRow(page, "INV-20844")).toContainText("Verifying")
  await ticks(page, 10)
  await expect(caseRow(page, "INV-20841")).toContainText("Needs approval")
  await page.getByRole("button", { name: /^History/ }).click()
  await expect(caseRow(page, "INV-20842")).toContainText("Verified")
  await expect(page.getByRole("button", { name: "Pause intake" })).toBeEnabled()
  await expect(page.getByRole("region", { name: "Outcome performance" })).toContainText("5 / 7")
})

test("conversation is a scoped secondary drawer and cannot bypass a case approval", async ({ page }) => {
  await enter(page); await open(page, "Invoice operations agent")
  await caseRow(page, "INV-20841").click()
  await page.getByRole("button", { name: "Message about this case" }).click()
  await expect(page.getByRole("dialog", { name: "Agent conversation" })).toContainText("This case only · INV-20841")
  await send(page, "continue")
  await expect(page.getByRole("log")).toContainText("cannot bypass")
  await close(page)
  await caseRow(page, "INV-20841").click()
  await page.getByRole("button", { name: "Approve $240 variance" }).click()
  await expect(page.getByRole("dialog")).toContainText("Queued")
  await ticks(page, 7)
  await expect(page.getByRole("dialog")).toContainText("Change applied · awaiting source read-back")
  await ticks(page, 3)
  await expect(page.getByRole("dialog")).toContainText("Completed for INV-20841 only")
  await close(page)
  await expect(page.getByRole("button", { name: "Pause intake" })).toBeVisible()
})

test("pause intake leaves admitted work running; steering persists without a conversation", async ({ page }) => {
  await enter(page); await open(page, "Invoice operations agent")
  await page.getByRole("button", { name: "Pause intake" }).click()
  await ticks(page, 10)
  await expect(caseRow(page, "INV-20845")).toContainText("Queued")
  await page.getByRole("button", { name: "Message agent" }).click()
  await page.locator("#aop-message").fill("Keep this unfinished direction")
  await close(page)
  await page.reload()
  await expect(page.getByRole("button", { name: "Resume intake" })).toBeVisible()
  await page.getByRole("button", { name: "Message agent" }).click()
  await expect(page.locator("#aop-message")).toHaveValue("Keep this unfinished direction")
  await send(page, "Resume intake")
  await close(page)
  await ticks(page, 1)
  await expect(caseRow(page, "INV-20845")).toContainText("Working")
})

test("configuration repair and explicit unsupported-scope repair precede deployment", async ({ page }) => {
  await enter(page); await open(page, "Employee onboarding agent")
  const deploy = page.getByRole("button", { name: "Deploy agent in demo" })
  await expect(deploy).toBeDisabled()
  await page.getByText("Operation checks", { exact: true }).click()
  await page.getByRole("button", { name: "What if payroll must be fully automated?" }).click()
  await expect(page.getByText("Automatic payroll provisioning isn’t supported.")).toBeVisible()
  await page.getByRole("button", { name: "Request this capability from MAXION" }).click()
  await expect(deploy).toBeDisabled()
  await expect(page.getByRole("button", { name: /Demo request AGX-104/ })).toBeDisabled()
  await page.getByRole("button", { name: "Keep payroll with its owner" }).click()
  await repairMapping(page)
  await expect(deploy).toBeEnabled()
  await deploy.click()
  await expect(page.getByRole("region", { name: "Agent operating status" })).toContainText("Watching incoming events")
  await ticks(page, 5)
  await caseRow(page, "JOIN-306").click()
  await expect(page.getByRole("region", { name: "Human fulfillment" })).toBeVisible()
  await page.getByRole("button", { name: "Attach owner confirmation" }).click()
  await expect(page.getByRole("alert")).toContainText("Enter the owner’s fulfillment reference")
  await page.getByLabel("Fulfillment reference").fill("PAYROLL-306/OWNER-2")
  await page.getByRole("button", { name: "Attach owner confirmation" }).click()
  await ticks(page, 5)
  await expect(page.getByRole("dialog")).toContainText("Completed for JOIN-306 only")
})

test("expired connection yields partial outcomes and recheck resumes without duplicate writes", async ({ page }) => {
  await enter(page); await open(page, "Invoice operations agent")
  await page.getByText("About this demo", { exact: true }).click()
  await page.getByRole("button", { name: "Simulate connection expiry" }).click()
  await ticks(page, 1)
  await expect(caseRow(page, "INV-20844")).toContainText("Partially complete")
  await caseRow(page, "INV-20844").click()
  await expect(page.getByRole("region", { name: "Partial outcome" })).toBeVisible()
  await page.getByText("Activity & evidence", { exact: true }).click()
  await expect(page.getByRole("dialog")).toContainText("Record writes: 1 · Duplicate writes: 0")
  await close(page)
  await page.getByRole("button", { name: "Reconnect notification account (demo)" }).click()
  await expect(page.getByRole("region", { name: "Connection repair" })).toContainText("Rechecking")
  await ticks(page, 5)
  await page.getByRole("button", { name: /^History/ }).click()
  await caseRow(page, "INV-20844").click()
  await expect(page.getByRole("dialog")).toContainText("Completed for INV-20844 only")
  await page.getByText("Activity & evidence", { exact: true }).click()
  await expect(page.getByRole("dialog")).toContainText("Record writes: 1 · Duplicate writes: 0")
})

test("separate recurring cycles retain success, missed execution and the next schedule", async ({ page }) => {
  await enter(page); await open(page, "Inventory operations agent")
  await expect(page.getByRole("region", { name: "Agent operating status" })).toContainText("14 Sept 2026")
  await ticks(page, 5)
  await page.getByRole("button", { name: /^Cycle history/ }).click()
  await expect(caseRow(page, "STOCK-901")).toContainText("Not completed")
  await expect(caseRow(page, "STOCK-902")).toContainText("Verified")
  await caseRow(page, "STOCK-901").click()
  await expect(page.getByRole("dialog")).toContainText("Missed cycle: ERP outage")
  await close(page)
  await page.getByText("About this demo", { exact: true }).click()
  await page.getByRole("button", { name: "Advance to next scheduled cycle" }).click()
  await page.getByRole("button", { name: /^Current work/ }).click()
  await expect(page.getByRole("region", { name: "Current work" })).toContainText("scheduled review")
  await expect(page.getByRole("region", { name: "Agent operating status" })).toContainText("15 Sept 2026")
})

test("Discovery retains its own landing hierarchy and hands off without deployment authority", async ({ page }) => {
  await page.goto("/maxion-prototype")
  await page.getByRole("button", { name: "Discover", exact: true }).click()
	await expect(page.getByRole("region", { name: "Discover interview workspace" })).toBeVisible()
  const packages = page.getByRole("region", { name: "Operational redesign packages" })
  await packages.locator("summary").click()
  await packages.getByRole("button", { name: /Employee onboarding/ }).click()
  await page.getByRole("button", { name: "Send to Agentix" }).click()
  await expect(page.getByRole("region", { name: "Deployment readiness" })).toBeVisible()
  await expect(page.getByRole("button", { name: "Deploy agent in demo" })).toBeDisabled()
})

test("natural-language entry reuses an existing agent and preserves unsupported briefs", async ({ page }) => {
  await enter(page)
  await page.getByRole("button", { name: "New agent", exact: true }).click()
  await page.getByLabel("Describe the responsibility").fill("Do something entirely different")
  await page.getByRole("button", { name: "Prepare agent" }).click()
  await expect(page.getByRole("status")).toContainText("Your brief is preserved")
  await page.getByLabel("Describe the responsibility").fill("Resolve invoice exceptions")
  await page.getByRole("button", { name: "Prepare agent" }).click()
  await expect(page.getByRole("status")).toContainText("no duplicate agent")
  expect(await page.evaluate(() => {
    const key = Array.from({ length: localStorage.length }, (_, index) => localStorage.key(index)).find((item) => item?.includes(":agentix-erp-modernization-"))
    return key ? JSON.parse(localStorage.getItem(key)!).value.runs.filter((run: { agentId: string }) => run.agentId === "invoice").length : 0
  })).toBe(7)
})

for (const width of [320, 375, 768, 1280, 1440]) {
	test(`Agentix operations and context remain accessible at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 })
    await enter(page)
    expect(await page.locator(".aop-root").evaluate(n => n.scrollWidth > n.clientWidth + 1)).toBe(false)
    await open(page, "Invoice operations agent")
    await page.getByRole("button", { name: "Message agent" }).click()
    await expect(page.locator("#aop-message")).toBeInViewport()
    await page.keyboard.press("Escape")
    await expect(page.getByRole("dialog")).toHaveCount(0)
    await expect(page.getByRole("button", { name: "Message agent" })).toBeFocused()
    await page.getByRole("button", { name: /^Agentix$/, exact: true }).click()
    await open(page, "Employee onboarding agent")
    await page.clock.resume()
  const scan = await new AxeBuilder({ page }).include(".aop-root").analyze()
    expect(scan.violations.filter(v => v.impact === "serious" || v.impact === "critical")).toEqual([])
    expect(await page.locator(".aop-root").evaluate(n => n.scrollWidth > n.clientWidth + 1)).toBe(false)
  })
}

test("dark mode, keyboard, focus containment and value disclosures remain usable", async ({ page }) => {
  await enter(page)
  await page.emulateMedia({ colorScheme: "dark", reducedMotion: "reduce" })
  await open(page, "Invoice operations agent")
  await page.getByText("How this is calculated", { exact: true }).click()
  await expect(page.getByRole("region", { name: "Outcome performance" })).toContainText("no labor savings or ROI is claimed")
  await page.getByRole("button", { name: "Message agent" }).click()
  await send(page, "Why this team?")
  await expect(page.getByRole("log")).toContainText("single ERP write")
  await page.keyboard.press("ControlOrMeta+k")
  await expect(page.getByRole("dialog", { name: "MAXION command menu" })).toHaveCount(0)
  await page.keyboard.press("Tab")
  expect(await page.evaluate(() => !!document.activeElement?.closest("dialog"))).toBe(true)
  await page.clock.resume()
  const scan = await new AxeBuilder({ page }).include(".aop-drawer").analyze()
  expect(scan.violations.filter(v => v.impact === "serious" || v.impact === "critical")).toEqual([])
  await page.keyboard.press("Escape")
  await page.keyboard.press("ControlOrMeta+k")
  await expect(page.getByRole("dialog", { name: "MAXION command menu" })).toBeVisible()
})

test("Agentix timers pause while another platform module is visible and resume on return", async ({ page }) => {
  await enter(page)
  await page.getByRole("navigation", { name: "Portal sections" }).getByRole("button", { name: "Dashboard", exact: true }).click()
  await ticks(page, 10)
  await page.getByRole("navigation", { name: "Portal sections" }).getByRole("button", { name: /^Agentix/ }).click()
  await open(page, "Invoice operations agent")
  await expect(caseRow(page, "INV-20842")).toContainText("Working")
  await ticks(page, 10)
  await page.getByRole("button", { name: /^History/ }).click()
  await expect(caseRow(page, "INV-20842")).toContainText("Verified")
})
