import { expect, test } from "@playwright/test"
import { readFile } from "node:fs/promises"

test.beforeEach(async ({ page }) => {
  await page.emulateMedia({ reducedMotion: "reduce" })
  await page.clock.install({ time: new Date("2026-09-11T09:00:00Z") })
  await page.clock.pauseAt(new Date("2026-09-11T09:00:01Z"))
})

test("a new owner can start, review, activate and resume a separate onboarding engagement", async ({ page }) => {
  await page.goto("/agentix-prototype")
  await page.getByRole("button", { name: "Assign work", exact: true }).click()
  await expect(page.getByRole("heading", { name: "What should an agent take on?" })).toBeVisible()
  await page.locator(".aop-template").filter({ hasText: "Employee onboarding" }).click()
  await expect(page.locator("#aop-brief")).toHaveValue(/approved new hire/)
  // The brief matches work the deployed team already does; a separate engagement is an explicit choice.
  await page.getByRole("button", { name: "Create a separate engagement instead" }).click()
  await expect(page.getByRole("heading", { name: "Review Employee onboarding 2", exact: true })).toBeVisible()
  await expect(page.getByText("From your brief").first()).toBeVisible()
  const activate = page.getByRole("button", { name: "Activate engagement" })
  await expect(activate).toBeDisabled()
  await page.getByText("UK · London analyst · standard access v4").click()
  await page.getByRole("button", { name: "Run the read-only check" }).click()
  await page.clock.runFor(4000)
  await expect(activate).toBeEnabled()
  await activate.click()
  await expect(page.getByRole("heading", { name: "Employee onboarding 2", exact: true })).toBeVisible()
  await page.getByRole("button", { name: "All engagements" }).click()
  await page.locator(".aop-agent-card").filter({ hasText: "Employee onboarding 2" }).click()
  await page.reload()
  await expect(page.getByRole("button", { name: "Pause intake" })).toBeVisible()
})

test("Agentix decisions are discoverable from the inbox and keep their case context", async ({ page }) => {
  await page.goto("/agentix-prototype")
  await page.getByRole("region", { name: "Your next actions" }).getByRole("button", { name: /Approve the \$240 price variance/ }).click()
  await expect(page.locator(".aop-case-head")).toContainText("INV-20841")
  await expect(page.locator(".ws-composer-context")).toContainText("INV-20841")
  // General chat can't approve; the decision stays in its card.
  await page.locator("#aop-composer-input").fill("continue")
  await page.getByRole("button", { name: "Send to the accountable agent" }).click()
  await expect(page.locator(".aop-latest")).toContainText("Not applied")
  await expect(page.getByRole("button", { name: "Approve $240 variance" })).toBeVisible()
  await page.getByRole("button", { name: "Work", exact: true }).click()
  await expect(page.getByRole("region", { name: "Needs you" })).toContainText("Approve the $240 price variance?")
  await expect(page.locator('[data-work="INV-20841"]')).toBeFocused()
})

test("Discovery keeps an unstarted brief, exposes planned deliverables and exports completed documents", async ({ page }) => {
  await page.goto("/discovery-prototype")
  await page.getByRole("button", { name: "New Discovery", exact: true }).click()
  await page.getByRole("button", { name: "ERP modernization", exact: true }).click()
  const brief = await page.getByRole("textbox", { name: "Discovery brief" }).inputValue()
  await page.getByRole("button", { name: "All discoveries", exact: true }).click()
  await page.getByRole("button", { name: "New Discovery", exact: true }).click()
  await expect(page.getByRole("textbox", { name: "Discovery brief" })).toHaveValue(brief)
  await page.getByRole("button", { name: "All discoveries", exact: true }).click()
  await page.getByRole("button", { name: "Resume ServiceNow financial-control integration, Working autonomously" }).click()
  await page.getByRole("button", { name: "Package", exact: true }).click()
  await expect(page.getByRole("heading", { name: "Planned deliverables", exact: true })).toBeVisible()
  await expect(page.getByRole("navigation", { name: "Deliverable list" }).getByRole("button")).toHaveCount(9)
  await expect(page.getByRole("button", { name: "Export all" })).toBeDisabled()
  await page.getByRole("button", { name: "All discoveries", exact: true }).click()
  await page.getByRole("button", { name: "Resume NorthBridge acquisition diligence, Completed" }).click()
  await page.getByRole("button", { name: "Package", exact: true }).click()
  const downloadPromise = page.waitForEvent("download")
  await page.getByRole("button", { name: "Export all" }).click()
  const download = await downloadPromise
  expect(download.suggestedFilename()).toBe("discovery-diligence-deliverables.md")
  const content = await readFile((await download.path())!, "utf8")
  expect(content.match(/^# /gm)).toHaveLength(9)
  expect(content).toContain("## Next steps")
  expect(content).toContain("Sources:")
})

test("mobile engagement navigation keeps the heading, tabs and composer reachable", async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 812 })
  await page.goto("/agentix-prototype")
  await page.getByRole("button", { name: "Assign work", exact: true }).click()
  await page.getByRole("button", { name: "Cancel", exact: true }).click()
  await page.locator(".aop-agent-card").filter({ hasText: "Revenue reconciliation" }).click()
  await expect(page.getByRole("heading", { name: "Revenue reconciliation", exact: true })).toBeInViewport()
  await expect(page.getByRole("tab", { name: /^Work/ })).toBeInViewport()
  await expect(page.locator("#aop-composer-input")).toBeInViewport()
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(375)
  await page.getByRole("button", { name: "Assign work", exact: true }).click()
  await expect(page.getByRole("dialog", { name: "Assign work to Revenue reconciliation" })).toBeInViewport()
})
