import { expect, test } from "@playwright/test"

test("runs, steers, recovers, and approves a Plan-bound local simulation", async ({ page }) => {
	const runtimeErrors: string[] = []
	page.on("console", (message) => { if (message.type() === "error") runtimeErrors.push(message.text()) })
	page.on("pageerror", (error) => runtimeErrors.push(error.message))

	await page.goto("/maxion-prototype")
	const navigation = page.getByRole("navigation", { name: "Portal sections" })
	await navigation.getByRole("button", { name: "Discover" }).click()
	const answer = page.getByRole("textbox", { name: "Answer MAX" })
	await answer.fill("The project owner approves Plan and the delivery run remains local-only.")
	await answer.press("Enter")
	await page.getByRole("button", { name: /^Gaps 1$/ }).click()
	await page.getByRole("button", { name: "Resolve from policy source" }).click()
	await page.getByRole("button", { name: "Create package for Plan" }).click()
	await page.getByRole("button", { name: "Approve plan" }).click()
	await page.getByRole("button", { name: "Send to Execute" }).click()

	await expect(page.getByRole("region", { name: "Execute delivery workspace" })).toBeVisible()
	await expect(page.getByText("Local simulation · Plan v1")).toBeVisible()
	await expect(page.getByText(/Production deploy requires a separate release path/)).toBeVisible()
	await page.getByRole("button", { name: "Start simulation" }).first().click()
	await page.getByRole("button", { name: "Pause safely" }).click()
	await expect(page.getByText("paused", { exact: true }).first()).toBeVisible()
	await page.getByRole("button", { name: "Resume run" }).click()

	const composer = page.getByRole("textbox", { name: "Steer this run" })
	await composer.fill("Keep the public API unchanged.")
	await page.getByRole("button", { name: "Send", exact: true }).click()
	await expect(page.getByRole("region", { name: "Run activity" })).toContainText("Keep the public API unchanged")
	await page.getByRole("button", { name: "Simulate failure" }).click()
	await expect(page.getByText("failed", { exact: true }).first()).toBeVisible()
	await page.getByRole("button", { name: "Retry stage" }).click()
	await expect(page.getByRole("button", { name: "Approve result" }).first()).toBeVisible({ timeout: 10_000 })
	await page.getByRole("button", { name: "Approve result" }).first().click()
	await expect(page.getByText("Simulation receipt ready")).toBeVisible()
	await expect(page.getByText("no production claim")).toBeVisible()
	expect(runtimeErrors).toEqual([])
})
