import { expect, test } from "@playwright/test"

for (const width of [375, 1440]) {
	test(`Projects preserves focus and readable input at ${width}px`, async ({ page }) => {
		await page.setViewportSize({ width, height: 960 })
		await page.emulateMedia({ reducedMotion: "reduce" })
		await page.goto("/maxion-prototype")
		const menu = page.getByRole("button", { name: "Open navigation", exact: true })
		if (await menu.isVisible()) await menu.click()
		await page.getByRole("navigation", { name: "Portal sections" }).getByRole("button", { name: "Projects", exact: true }).click()
		const projects = page.locator(".mxp-projects-page")
		await expect(projects.getByRole("button", { name: "List view" })).toHaveAttribute("aria-pressed", "true")
		const trigger = projects.getByRole("button", { name: "Create Project", exact: true })
		await trigger.click()
		const dialog = page.getByRole("dialog", { name: "Create new project" })
		const name = dialog.getByRole("textbox", { name: /Project name/ })
		await expect(name).toBeFocused()
		const overlay = await projects.locator(".mxp-dialog-layer").boundingBox()
		expect(overlay!.x).toBe(0)
		expect(overlay!.width).toBe(width)
		expect(await name.evaluate(element => parseFloat(getComputedStyle(element).fontSize))).toBeGreaterThanOrEqual(16)
		await name.fill("Compact project workspace")
		await page.keyboard.press("Escape")
		await expect(dialog).toHaveCount(0)
		await expect(trigger).toBeFocused()
		await trigger.click()
		await expect(name).toHaveValue("Compact project workspace")
		await dialog.getByRole("button", { name: "Cancel" }).click()
		await expect(trigger).toBeFocused()
		await projects.getByRole("button", { name: "Grid view" }).click()
		await expect(projects.locator(".mxp-project-collection")).toHaveClass(/is-grid/)
	})

	test(`Agentix fleet reflows without clipped cards at ${width}px`, async ({ page }) => {
		await page.setViewportSize({ width, height: 960 })
		await page.emulateMedia({ reducedMotion: "reduce" })
		await page.goto("/agentix-prototype")
		const cards = page.locator(".aop-agent-card")
		await expect(cards).toHaveCount(4)
		for (const card of await cards.all()) {
			const bounds = await card.boundingBox()
			expect(bounds).not.toBeNull()
			expect(bounds!.x).toBeGreaterThanOrEqual(0)
			expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(width)
			expect(await card.evaluate(element => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
			if (width === 1440) expect(bounds!.height).toBeLessThan(180)
		}
		await cards.filter({ hasText: "Revenue reconciliation" }).click()
		await expect(page.getByRole("textbox", { name: /^Message Revenue coordinator/ })).toBeInViewport()
	})
}

test("phone Discovery keeps both navigation targets reachable and metrics compact", async ({ page }) => {
	await page.setViewportSize({ width: 375, height: 960 })
	await page.emulateMedia({ reducedMotion: "reduce" })
	await page.goto("/maxion-prototype")
	await page.getByRole("button", { name: "Open navigation", exact: true }).click()
	await page.getByRole("navigation", { name: "Portal sections" }).getByRole("button", { name: "Discover", exact: true }).click()
	await page.getByRole("button", { name: "Resume ServiceNow financial-control integration, Working autonomously" }).click()
	await page.getByRole("button", { name: "Autonomy", exact: true }).click()
	const metrics = await page.locator(".autonomy-value-strip > div").evaluateAll(elements => elements.map(element => ({ x: element.getBoundingClientRect().x, y: element.getBoundingClientRect().y })))
	expect(metrics[0].y).toBe(metrics[1].y)
	expect(metrics[0].x).toBeLessThan(metrics[1].x)
	await page.getByRole("button", { name: "All discoveries", exact: true }).click()
	await expect(page.getByRole("heading", { name: "Continue where MAX left off." })).toBeVisible()
	await page.getByRole("button", { name: "Resume NorthBridge acquisition diligence, Completed" }).click()
	await page.getByRole("button", { name: "Package", exact: true }).click()
	const reader = page.locator(".deliverable-reader")
	const readerBounds = await reader.boundingBox()
	expect(readerBounds!.width).toBe(375)
	expect(readerBounds!.height).toBeGreaterThan(240)
	await page.getByRole("navigation", { name: "Deliverable list" }).getByRole("button", { name: /Technical assessment/ }).click()
	await expect(reader.getByRole("heading", { name: "Technical assessment", exact: true })).toBeVisible()
	await page.getByRole("button", { name: "Open navigation", exact: true }).click()
	await expect(page.getByRole("navigation", { name: "Portal sections" })).toBeVisible()
})
