import { expect, test } from "@playwright/test"

test.beforeEach(async ({ page }) => {
  await page.emulateMedia({ reducedMotion: "reduce" })
  await page.clock.install({ time: new Date("2026-09-11T09:00:00Z") })
  await page.clock.pauseAt(new Date("2026-09-11T09:00:01Z"))
})

test("a separate engagement persists its own definition, work and conversation without changing the original", async ({ page }) => {
  await page.goto("/agentix-prototype")
  await page.getByRole("button", { name: "Assign work", exact: true }).click()
  await page.locator("#aop-brief").fill("Review EMEA invoices against the approved purchasing policy")
  await page.getByRole("button", { name: "Create a separate engagement" }).click()
  await page.getByLabel("Engagement name", { exact: true }).fill("EMEA invoice controls")
  await page.getByLabel("Accountable owner").fill("Priya S.")
  await page.getByLabel("Operating scope", { exact: true }).fill("Only EMEA invoices; request explicit price-variance approvals")
  await page.getByRole("button", { name: "All engagements", exact: true }).click()
  await page.locator(".aop-agent-card").filter({ hasText: "EMEA invoice controls" }).click()
  await expect(page.getByLabel("Accountable owner")).toHaveValue("Priya S.")
  await page.getByRole("button", { name: "Run the read-only check" }).click()
  await page.clock.runFor(4000)
  await page.getByRole("button", { name: "Activate engagement" }).click()
  await expect(page.getByRole("heading", { name: "EMEA invoice controls", exact: true })).toBeVisible()
  await expect(page.locator(".aop-now")).toContainText("Ready for incoming work")
  // New work arrives through the engagement's trigger (the demo's incoming event), not a sample-case button.
  await page.getByRole("button", { name: "Controls", exact: true }).click()
  await page.getByRole("button", { name: "Add", exact: true }).click()
  await page.getByRole("button", { name: "Close controls" }).click()
  await page.getByRole("button", { name: "Controls", exact: true }).click()
  await page.getByRole("button", { name: "Skip", exact: true }).click()
  await page.getByRole("button", { name: "Close controls" }).click()
  await page.locator(".aop-work-row").first().click()
  await expect(page.getByRole("button", { name: "Approve $240 variance" })).toBeVisible()
  await page.locator("#aop-composer-input").fill("continue")
  await page.getByRole("button", { name: "Send to the accountable agent" }).click()
  await expect(page.locator(".aop-latest")).toContainText("Not applied")
  await page.reload()
  await expect(page.getByRole("heading", { name: "EMEA invoice controls", exact: true })).toBeVisible()
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem("maxion-agentix-operations-v4")!))
  expect(Object.keys(saved.engagements)).toHaveLength(5)
  const created = Object.values(saved.engagements).find((engagement: { name: string }) => engagement.name === "EMEA invoice controls") as { id: string; scope: string; origin: { kind: string } }
  expect(created.scope).toContain("Only EMEA")
  expect(created.origin.kind).toBe("prompt")
  expect(saved.work.find((item: { reference: string }) => item.reference === "INV-20841").flags.approved).toBeFalsy()
  expect(saved.work.filter((item: { engagementId: string }) => item.engagementId === created.id)).toHaveLength(1)
})

test("the full approval action and the composer remain visible at normal laptop height", async ({ page }) => {
  await page.setViewportSize({ width: 1280, height: 720 })
  await page.goto("/agentix-prototype")
  await page.locator(".aop-agent-card").filter({ hasText: "Revenue reconciliation" }).click()
  await page.getByRole("button", { name: "Review details", exact: true }).first().click()
  const approval = await page.getByRole("button", { name: "Approve $240 variance" }).boundingBox()
  const work = await page.locator(".aop-eng-scroll").boundingBox()
  const composer = await page.locator(".aop-eng-dock .ws-composer").boundingBox()
  expect(approval!.y + approval!.height).toBeLessThanOrEqual(work!.y + work!.height)
  expect(composer!.y + composer!.height).toBeLessThanOrEqual(720)
  await page.locator("#aop-composer-input").fill("Keep this case draft")
  await page.getByRole("button", { name: "Details", exact: true }).click()
  await page.keyboard.press("Escape")
  await expect(page.locator("#aop-composer-input")).toHaveValue("Keep this case draft")
  await expect(page.getByRole("button", { name: "Approve $240 variance" })).toBeVisible()
})

test("mobile opens the conversation over the work without losing a case draft", async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 812 })
  await page.goto("/agentix-prototype")
  await page.locator(".aop-agent-card").filter({ hasText: "Revenue reconciliation" }).click()
  await page.getByRole("button", { name: "Review details", exact: true }).first().click()
  const input = page.locator("#aop-composer-input")
  await input.fill("Keep the Northwind decision scoped")
  await page.getByRole("button", { name: /^Conversation/ }).click()
  await expect(page.getByRole("region", { name: "Conversation" })).toBeVisible()
  await expect(input).toHaveValue("Keep the Northwind decision scoped")
  await expect(input).toBeFocused()
  const box = await page.locator(".aop-conversation .ws-composer").boundingBox()
  expect(box!.y + box!.height).toBeLessThanOrEqual(812)
  await page.getByRole("button", { name: "Close conversation" }).click()
  await expect(page.getByRole("button", { name: "Approve $240 variance" })).toBeVisible()
  await expect(input).toHaveValue("Keep the Northwind decision scoped")
})

for (const width of [1440, 375]) test(`engagement review fields use the designed layout at ${width}px`, async ({ page }) => {
  await page.setViewportSize({ width, height: 900 })
  await page.goto("/agentix-prototype")
  await page.getByRole("button", { name: "Assign work", exact: true }).click()
  await page.locator(".aop-template").filter({ hasText: "Employee onboarding" }).click()
  await page.getByRole("button", { name: "Create a separate engagement instead" }).click()
  const fields = page.locator(".aop-definition-fields")
  expect(await fields.evaluate(node => getComputedStyle(node).display)).toBe("grid")
  for (const label of ["Engagement name", "Accountable owner", "Operating scope"]) {
    const input = page.getByLabel(label, { exact: true })
    const bounds = await input.boundingBox()
    expect(bounds!.width).toBeGreaterThan(width === 375 ? 240 : 280)
    expect(await input.evaluate(node => getComputedStyle(node).borderTopStyle)).toBe("solid")
    expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(width)
  }
  const name = await page.getByLabel("Engagement name", { exact: true }).boundingBox()
  const owner = await page.getByLabel("Accountable owner").boundingBox()
  if (width > 900) expect(owner!.x).toBeGreaterThanOrEqual(name!.x + name!.width)
  else expect(owner!.y).toBeGreaterThanOrEqual(name!.y + name!.height)
})

test("Discovery shows current work before supporting metrics on mobile and keeps operation status out of context", async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 812 })
  await page.goto("/discovery-prototype")
  await page.getByRole("button", { name: "Resume ServiceNow financial-control integration, Working autonomously" }).click()
  await page.getByRole("button", { name: "Thread", exact: true }).click()
  await expect(page.locator(".thread-inspector")).not.toContainText("Current operation")
  await expect(page.getByRole("textbox", { name: "Message MAX" })).toBeVisible()
  await page.getByRole("button", { name: "Autonomy", exact: true }).click()
  await page.clock.runFor(500)
  const trace = await page.getByRole("button", { name: /Inspect the current work trace/ }).boundingBox()
  const metrics = await page.getByRole("region", { name: "Work handled by MAX" }).boundingBox()
  expect(trace!.y + trace!.height).toBeLessThanOrEqual(812)
  expect(trace!.y).toBeLessThan(metrics!.y)
  const progress = await page.locator(".autonomy-progress-summary").evaluate(node => ({ width: node.clientWidth, scroll: node.scrollWidth }))
  expect(progress.scroll).toBeLessThanOrEqual(progress.width)
  // Long rotating activity text must fit its own card, not merely a clipped page.
  for (const width of [375, 1280]) {
    await page.setViewportSize({ width, height: 812 })
    const line = page.locator(".dsc-now-line").first()
    await line.locator(".dsc-now-text").evaluate(node => {
      node.textContent = "Comparing system ownership against Change and incident management evidence from ServiceNow and the approved finance operating context"
    })
    const bounds = await line.evaluate(node => {
      const text = node.querySelector(".dsc-now-text")!
      return { lineRight: node.getBoundingClientRect().right, textRight: text.getBoundingClientRect().right, cardRight: node.closest(".autonomy-current")!.getBoundingClientRect().right, display: getComputedStyle(node).display, fontSize: parseFloat(getComputedStyle(text).fontSize) }
    })
    expect(bounds.display).toBe("flex")
    expect(bounds.fontSize).toBeGreaterThanOrEqual(12)
    expect(bounds.textRight).toBeLessThanOrEqual(bounds.lineRight)
    expect(bounds.lineRight).toBeLessThanOrEqual(bounds.cardRight)
  }
})

test("a Discovery status question or negation never becomes a sponsor-send instruction", async ({ page }) => {
  await page.goto("/discovery-prototype")
  await page.getByRole("button", { name: "Resume ServiceNow financial-control integration, Working autonomously" }).click()
  await page.getByRole("button", { name: "Thread", exact: true }).click()
  const composer = page.getByRole("textbox", { name: "Message MAX" })
  for (const text of ["What is the status?", "Do not send the sponsor a status update", "What is the invitation status?"]) {
    await composer.fill(text)
    await composer.press("Enter")
    await page.clock.runFor(250)
    await expect(page.locator(".max-message").last()).toContainText("No sponsor update was sent.")
    await expect(page.locator(".max-message").last()).not.toContainText("Sent and verified")
  }
  await composer.fill("Send the sponsor a status update")
  await composer.press("Enter")
  await page.clock.runFor(250)
  await expect(page.locator(".max-message").last()).toContainText("Status update sent to the approved sponsor")
  await expect(page.locator(".max-message").last()).not.toContainText("Demo")
})
