import { ArrowLeft, ArrowRight, ArrowUp, CaretDown, ChatCircleText, CheckCircle, FileText, Info, MagnifyingGlass, Pause, Play, Plus, ShieldCheck, Users, X } from "@phosphor-icons/react"
import { useEffect, useRef, useState, type KeyboardEvent } from "react"
import type { AgentixAttention, AgentixIntentSignal } from "./AgentixInitiativesPage"
import { WORKFLOWS, type WorkflowId } from "./initiatives"
import { Button } from "./WorkspaceParts"
import { AGENT_NAMES, DEMO_TICK_MS, OPERATIONS_KEY, admitOccurrence, agentLabel, initialOperations, isTerminal, matchAgent, messageAgent, needsAttention, nextSchedule, readOperations, readiness, setMapping, tickOperations, updateAgent, updateRun, workflowFor, type AgentAction, type OperationRun, type RunAction } from "./operationsState"
import { AgentMark, Fleet, ReadinessPanel, RunDetail, RunsList, Status, ValueSummary } from "./OperationsViews"
import "./operations.css"

type Panel = { kind: "case"; runId: string } | { kind: "message"; runId?: string } | { kind: "scope" } | null
export function DeployedAgentsPage({ intentSignal, onAttentionChange, onOpenDiscovery }: { intentSignal?: AgentixIntentSignal | null; onAttentionChange?: (attention: AgentixAttention) => void; onOpenDiscovery: (id: WorkflowId) => void }) {
  const [state, setState] = useState(readOperations)
  const [creating, setCreating] = useState(false)
  const [query, setQuery] = useState("")
  const [filter, setFilter] = useState("all")
  const [history, setHistory] = useState(false)
  const [panel, setPanel] = useState<Panel>(null)
  const [notice, setNotice] = useState("")
  const [storageError, setStorageError] = useState(false)
  const [confirmReset, setConfirmReset] = useState(false)
  const [discoveryChoices, setDiscoveryChoices] = useState(false)
  const root = useRef<HTMLDivElement>(null)
  const dialog = useRef<HTMLDialogElement>(null)
  const returnFocus = useRef<HTMLElement | null>(null)
  const messages = useRef<HTMLDivElement>(null)
  const seen = useRef(0)
  const agent = state.selected ? state.agents[state.selected] : null
  const workflow = agent ? workflowFor(agent.id) : null
  const runs = agent ? state.runs.filter(run => run.agentId === agent.id) : state.runs
  const selectedRun = panel && "runId" in panel ? state.runs.find(run => run.id === panel.runId && run.agentId === agent?.id) : undefined
  const openAgent = (id: WorkflowId) => { setState(s => ({ ...s, selected: id })); setCreating(false); setPanel(null); setHistory(false); setFilter("all"); setNotice("") }
  const openPanel = (next: Panel) => { returnFocus.current = document.activeElement as HTMLElement; setPanel(next) }
  const closePanel = () => { setPanel(null); window.requestAnimationFrame(() => returnFocus.current?.isConnected && returnFocus.current.focus()) }
  const onDialogKeyDown = (event: KeyboardEvent<HTMLDialogElement>) => {
    if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "k") { event.preventDefault(); event.stopPropagation(); return }
    if (event.key !== "Tab") return
    const controls = Array.from(event.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),textarea:not(:disabled),select:not(:disabled),summary,[tabindex="0"]')).filter(el => el.getClientRects().length > 0)
    const first = controls[0], last = controls.at(-1)
    if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus() }
    else if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus() }
  }
  const act = (action: AgentAction) => { if (agent) setState(s => updateAgent(s, agent.id, action)) }
  const runAct = (run: OperationRun, action: RunAction, evidence?: string) => setState(s => updateRun(s, run.id, action, evidence))
  const prepare = (id: WorkflowId, origin: "discovery" | "prompt", brief = "") => {
    openAgent(id)
    setState(s => ({ ...s, newBrief: "", agents: { ...s.agents, [id]: s.agents[id].status === "draft" ? { ...s.agents[id], origin, brief, automaticPayroll: origin === "prompt" && /automat.*payroll|payroll.*automat/i.test(brief), checked: false } : s.agents[id] } }))
    setNotice(state.agents[id].status === "draft" ? "Design and context received. Review readiness before deployment; no work has started." : "An agent already owns this responsibility. Its deployment, cases and history are preserved—no duplicate agent was created.")
  }
  useEffect(() => { try { localStorage.setItem(OPERATIONS_KEY, JSON.stringify(state)); setStorageError(false) } catch { setStorageError(true) } }, [state])
  useEffect(() => { const timer = window.setInterval(() => setState(tickOperations), DEMO_TICK_MS); return () => window.clearInterval(timer) }, [])
  useEffect(() => { onAttentionChange?.({ count: state.runs.filter(needsAttention).length + Object.values(state.agents).filter(a => a.status === "draft" && readiness(a) !== "ready").length, approval: state.runs.some(r => r.phase === "approval"), audience: state.runs.some(r => r.phase === "human") }) }, [state.runs, state.agents, onAttentionChange])
  const intentActions = useRef<(intent: NonNullable<AgentixIntentSignal>["intent"]) => void>(() => undefined)
  intentActions.current = (intent) => {
    if (intent.type === "workflow") openAgent(intent.id)
    else if (intent.type === "import") prepare(intent.id, "discovery")
    else if (intent.type === "create") { setCreating(true); setPanel(null) }
    else if (intent.type === "decision") { const id = intent.id === "approval" ? "invoice" : "onboarding"; openAgent(id); const run = state.runs.find(r => r.agentId === id && needsAttention(r)); if (run) setPanel({ kind: "case", runId: run.id }) }
    else { setState(s => ({ ...s, selected: null })); setCreating(false); setPanel(null); setFilter(intent.id === "today" ? "attention" : "all") }
  }
  useEffect(() => {
    if (!intentSignal || intentSignal.tick === seen.current) return
    seen.current = intentSignal.tick
    intentActions.current(intentSignal.intent)
  }, [intentSignal])
  useEffect(() => { if (panel && dialog.current && !dialog.current.open) dialog.current.showModal(); else if (!panel && dialog.current?.open) dialog.current.close() }, [panel])
  useEffect(() => { if (panel?.kind === "message") messages.current?.scrollTo?.({ top: messages.current.scrollHeight }) }, [agent?.messages.length, panel?.kind])
  useEffect(() => { if (!root.current?.closest("[hidden]")) root.current?.querySelector<HTMLHeadingElement>(".aop-page-heading h1")?.focus({ preventScroll: true }) }, [state.selected, creating])
  const submitBrief = () => { const text = state.newBrief.trim(); const id = matchAgent(text); if (id) prepare(id, "prompt", text); else setNotice("This demo supports service desk, invoice operations, onboarding and inventory. Your brief is preserved; arbitrary agent generation isn’t connected.") }
  const submitMessage = () => { if (agent) setState(s => messageAgent(s, agent.id, selectedRun ? agent.caseDrafts?.[selectedRun.id] ?? "" : agent.draft, panel?.kind === "message" ? panel.runId : undefined)); root.current?.querySelector<HTMLTextAreaElement>("#aop-message")?.focus() }
  const liveCount = Object.values(state.agents).filter(a => a.status !== "draft").length
  return <div className="aop-root" ref={root}>
    <header className="aop-topbar"><div><button className="aop-breadcrumb" onClick={() => { setState(s => ({ ...s, selected: null })); setCreating(false); setPanel(null); setFilter("all") }}>{agent || creating ? <ArrowLeft size={16} /> : <span className="aop-brand-mark"><AgentMark id="service" /></span>}Agentix</button>{agent || creating ? <><span className="aop-slash">/</span><span>{creating ? "New agent" : AGENT_NAMES[agent!.id]}</span></> : null}</div><span className="aop-demo-badge"><Info size={14} />Interactive demo</span></header>
    <main className="aop-main" aria-label="Agentix workspace">
      {storageError ? <p className="aop-notice" role="alert">Browser storage is unavailable. Work remains usable, but changes won’t survive refresh.</p> : null}
      {notice ? <p className="aop-notice" role="status">{notice}</p> : null}
      {creating ? <section className="aop-create"><div className="aop-page-heading"><span className="aop-eyebrow">An ongoing responsibility. An accountable agent.</span><h1 tabIndex={-1}>What should your agent take care of?</h1><p>Start with a Discovery design or describe the responsibility. Agentix proposes the smallest team, checks readiness and asks only what it can’t infer.</p></div><form className="aop-brief" onSubmit={e => { e.preventDefault(); submitBrief() }}><label htmlFor="aop-brief">Describe the responsibility</label><textarea id="aop-brief" value={state.newBrief} onChange={e => setState(s => ({ ...s, newBrief: e.target.value }))} maxLength={2000} placeholder="Coordinate onboarding for every approved new hire…" rows={4} /><div><span>No model, agent-count or workflow-builder setup.</span><button type="submit" className="agw-button is-primary" disabled={!state.newBrief.trim()}>Prepare agent<ArrowRight size={16} /></button></div></form><button className="aop-discovery-start" onClick={() => setDiscoveryChoices(!discoveryChoices)} aria-expanded={discoveryChoices}><FileText size={20} /><span>Use a completed Discovery<small>Bring the process, evidence and controls with you.</small></span><CaretDown size={18} /></button>{discoveryChoices ? <div className="aop-designs">{WORKFLOWS.map(w => <button key={w.id} onClick={() => prepare(w.id, "discovery")}><span>{w.title}<small>Approved design v1 · {w.sources.length} sources</small></span><ArrowRight size={16} /></button>)}</div> : null}<p className="aop-small">Four representative responsibilities are available in this prototype. Existing agents are reused; importing the same design doesn’t create duplicates.</p></section> : !agent ? <>
        <div className="aop-page-heading aop-heading-row"><div><span className="aop-eyebrow">Your autonomous operations</span><h1 tabIndex={-1}>Deployed agents</h1><p>{liveCount} deployed agents own the work. Open an agent to see its workload, resolve an exception or give direction.</p></div><Button primary onClick={() => { setCreating(true); setNotice("") }}><Plus size={17} />New agent</Button></div>
        <section className="aop-fleet-summary" aria-label="Operations summary"><span><span className="aop-status-dot" /><strong>{liveCount}</strong> deployed</span><span><strong>{state.runs.filter(r => !isTerminal(r)).length}</strong> open cases</span><span><strong>{state.runs.filter(needsAttention).length}</strong> need your decision</span><span><strong>{state.runs.filter(r => r.phase === "verified").length}</strong> verified outcomes</span></section>
        <div className="aop-toolbar"><div className="aop-segments" aria-label="Agent filter"><button aria-pressed={filter === "all"} onClick={() => setFilter("all")}>All agents</button><button aria-pressed={filter === "attention"} onClick={() => setFilter("attention")}>Needs attention</button></div><label className="aop-search"><MagnifyingGlass size={17} /><input aria-label="Search agents" value={query} onChange={e => setQuery(e.target.value)} placeholder="Find an agent…" /></label></div><Fleet state={state} query={query} filter={filter} onOpen={openAgent} />
        <p className="aop-quiet-note"><ShieldCheck size={16} />Each agent has one owner, a defined scope and an outcome contract for every case. A waiting case doesn’t stop the others.</p>
      </> : <>
        <div className="aop-page-heading aop-heading-row"><div className="aop-agent-heading"><AgentMark id={agent.id} /><div><div className="aop-agent-eyebrow"><Status label={agentLabel(agent, runs)} active={agent.status === "active" && readiness(agent) === "ready"} attention={readiness(agent) !== "ready"} /><span>{agent.status === "draft" ? "Proposed deployment" : `Deployed v${agent.version}`}</span></div><h1 tabIndex={-1}>{AGENT_NAMES[agent.id]}</h1><p>{workflow!.description}</p></div></div><div className="aop-actions">{agent.status !== "draft" ? <Button onClick={() => act(agent.status === "paused" ? "resume-intake" : "pause-intake")} disabled={agent.status === "paused" && readiness(agent) !== "ready"}>{agent.status === "paused" ? <Play size={16} /> : <Pause size={16} />}{agent.status === "paused" ? "Resume intake" : "Pause intake"}</Button> : null}<Button onClick={() => openPanel({ kind: "message" })}><ChatCircleText size={18} />Message agent</Button></div></div>
        {agent.status === "paused" ? <p className="aop-notice" role="status">New intake is paused. Already-admitted cases continue; queued work waits. Use a case’s pause control to stop its next action.</p> : null}
        {agent.holdNotifications ? <p className="aop-notice" role="status">Pending outbound notifications are held by your instruction. Required delivery obligations stay incomplete.</p> : null}
        {agent.connection === "expired" || agent.checking && agent.status !== "draft" ? <section className="aop-repair aop-runtime-repair" aria-label="Connection repair"><h2>{agent.checking ? "Rechecking the restored connection…" : "Notifications are waiting. Other permitted work continues."}</h2><p>{agent.checking ? "Checking the approved audience and notification operation before resuming only the outstanding sends." : "The notification connection expired. Confirmed record changes are preserved; no write will be repeated."}</p><small>Owner: integration administrator · affected obligation: notify the approved audience</small><Button primary disabled={agent.checking} onClick={() => act("reconnect")}>{agent.checking ? "Rechecking…" : "Reconnect notification account (demo)"}</Button></section> : null}
        {agent.status === "draft" ? <>
          <section className="aop-proposal" aria-label="Proposed operating plan"><div className="aop-section-title"><h2>The responsibility</h2><button className="aop-text-button" onClick={() => onOpenDiscovery(agent.id)}><FileText size={15} />{agent.origin === "discovery" ? "From Discovery v1" : "Brief + Discovery context"}</button></div><p>{workflow!.outcome}</p>{agent.brief ? <blockquote>{agent.brief}</blockquote> : null}<dl><dt>When it acts</dt><dd>{workflow!.trigger}</dd><dt>Boundaries</dt><dd>{workflow!.boundary}</dd><dt>Accountable owner</dt><dd>{workflow!.owner}</dd></dl><p className="aop-small">One coordinator and two scoped specialists. Payroll remains a human-owned obligation unless separately certified. No new infrastructure is created by this demo.</p></section>
          <ReadinessPanel agent={agent} onAction={act} onMapping={value => setState(s => setMapping(s, agent.id, value))} />
          <div className="aop-deploy-bar"><div><strong>{readiness(agent) === "ready" ? "Ready for your activation" : "Deployment waits for readiness"}</strong><span>{readiness(agent) === "ready" ? "Activate the reviewed scope and start accepting approved hire events." : "Resolve the identified requirement; don’t repeat the Discovery interview."}</span></div><Button primary disabled={readiness(agent) !== "ready"} onClick={() => act("deploy")}>Deploy agent in demo<ArrowRight size={16} /></Button></div>
        </> : <>
          <section className="aop-operating-strip" aria-label="Agent operating status"><div><span className="aop-status-dot" /><span>{agent.status === "paused" ? "Intake paused" : agent.id === "inventory" ? "Schedule enabled" : "Watching incoming events"}<small>{agent.id === "inventory" ? `Next: ${new Date(agent.nextOccurrence).toLocaleString("en-GB", { timeZone: "Europe/London", dateStyle: "medium", timeStyle: "short" })} · London` : workflow!.trigger}</small></span></div><button onClick={() => openPanel({ kind: "scope" })}><Users size={17} />{workflow!.team.length === 1 ? "1 agent" : "1 coordinator · 2 specialists"}<ArrowRight size={15} /></button></section>
          <div className="aop-toolbar"><div className="aop-segments" aria-label="Work view"><button aria-pressed={!history} onClick={() => { setHistory(false); setFilter("all") }}>Current work <span>{runs.filter(r => !isTerminal(r)).length}</span></button><button aria-pressed={history} onClick={() => { setHistory(true); setFilter("all") }}>{agent.id === "inventory" ? "Cycle history" : "History"} <span>{runs.filter(isTerminal).length}</span></button></div>{!history ? <button className="aop-filter" aria-pressed={filter === "attention"} onClick={() => setFilter(filter === "all" ? "attention" : "all")}>Needs you <span>{runs.filter(needsAttention).length}</span></button> : <span className="aop-small">Each occurrence retains its own result</span>}</div>
          <RunsList runs={runs} history={history} filter={filter} onOpen={run => openPanel({ kind: "case", runId: run.id })} />
          <ValueSummary runs={runs} />
        </>}
      </>}
      <footer className="aop-demo-controls"><details><summary><Info size={15} />About this demo<CaretDown size={15} /></summary><p>Simulated deployed agents and connected systems. Cases advance independently while MAXION is open—even when this module or conversation is closed. Closing the browser stops this frontend simulation; production background execution is not implemented here.</p><p>Demo clock: {new Date(state.clock).toLocaleString("en-GB", { timeZone: "UTC", dateStyle: "medium", timeStyle: "short" })} UTC. One demo minute per tick. Incoming service and invoice events arrive periodically. At 200 case records, demo intake stops and retains history. No real email, ERP, Teams or HR action occurs.</p><div className="aop-actions"><Button onClick={() => setState(nextSchedule)} disabled={state.agents.inventory.status !== "active" || readiness(state.agents.inventory) !== "ready" || state.runs.length >= 200}>Advance to next scheduled cycle</Button>{agent?.status !== "draft" && agent ? <><Button disabled={state.runs.length >= 200} onClick={() => setState(s => admitOccurrence(s, agent.id, `demo-event:${s.clock}`))}>Add incoming event</Button><Button onClick={() => act("expire")} disabled={agent.connection === "expired"}>Simulate connection expiry</Button></> : null}<button className="aop-text-button" onClick={() => setConfirmReset(true)}>Reset demo</button></div>{confirmReset ? <div className="aop-reset"><p>Reset deployed agents, cases and messages? Saved Discovery work and earlier demo versions are kept.</p><Button onClick={() => { setState(initialOperations()); setConfirmReset(false); setCreating(false); setPanel(null) }}>Reset Agentix demo</Button><Button onClick={() => setConfirmReset(false)}>Keep current state</Button></div> : null}</details></footer>
    </main>
    <dialog className="aop-drawer" ref={dialog} onKeyDown={onDialogKeyDown} onCancel={e => { e.preventDefault(); closePanel() }} onClose={() => { if (panel) closePanel() }} aria-label={panel?.kind === "message" ? "Agent conversation" : panel?.kind === "scope" ? "Agent responsibilities" : "Case details"}>
      <header><div><small>{agent ? AGENT_NAMES[agent.id] : "Agentix"}</small><strong>{panel?.kind === "message" ? "Give direction" : panel?.kind === "scope" ? "Team & operating scope" : selectedRun?.reference}</strong></div><button className="aop-icon-button" aria-label="Close details" onClick={closePanel}><X size={20} /></button></header>
      {agent && panel?.kind === "case" && selectedRun ? <div className="aop-drawer-scroll"><RunDetail key={selectedRun.id} run={selectedRun} agent={agent} onAction={(action, evidence) => runAct(selectedRun, action, evidence)} onSteer={() => setPanel({ kind: "message", runId: selectedRun.id })} /></div> : null}
      {agent && panel?.kind === "scope" ? <div className="aop-drawer-scroll"><section><h2>One accountable coordinator.</h2><p>{workflow!.teamReason}</p><div className="aop-team" aria-label="Agent team">{workflow!.team.map(member => <details key={member.id}><summary><Users size={18} /><span>{member.name}<small>{member.id === "coordinator" ? "Owns each outcome" : "Scoped specialist"}</small></span><Status label={runs.some(r => r.phase === "working" && (member.id === "coordinator" ? r.step >= 2 : r.step < 2)) ? "Working" : "Available"} active /><CaretDown size={15} /></summary><p>{member.responsibility}</p><small>{member.tools}</small></details>)}</div></section><section><h3>Authority & ownership</h3><p>{workflow!.boundary}</p><p>Owner: {workflow!.owner} · Deployment v{agent.version} · at most 3 admitted cases concurrently in this demo.</p></section><details className="aop-disclosure"><summary>Discovery sources<CaretDown size={16} /></summary>{workflow!.sources.map(source => <div key={source.title}><strong>{source.title}</strong><p>{source.detail}</p></div>)}<Button onClick={() => { closePanel(); onOpenDiscovery(agent.id) }}>Open Discovery design</Button></details><details className="aop-disclosure"><summary>Deployment record<CaretDown size={16} /></summary>{agent.notes.map((note, i) => <p key={i}>{note}</p>)}</details></div> : null}
      {agent && panel?.kind === "message" ? <><div className="aop-conversation-scope"><ShieldCheck size={16} /><span>{selectedRun ? `This case only · ${selectedRun.reference}` : "Agent scope · all future and unresolved work"}</span>{selectedRun ? <button className="aop-text-button" onClick={() => setPanel({ kind: "message" })}>Agent scope</button> : null}</div><div className="aop-chat-scroll" ref={messages} tabIndex={0} role="log" aria-label="Agent messages"><article className="aop-agent-intro"><CheckCircle size={22} /><h2>Work continues without this conversation.</h2><p>Ask for a status update or give a scoped instruction. Decisions that need exact approval stay attached to their cases.</p></article>{agent.messages.filter(m => panel.runId ? m.runId === panel.runId : !m.runId).map(m => <article key={m.id} className={`aop-message is-${m.role}`}><span>{m.role === "user" ? "You" : AGENT_NAMES[agent.id]}</span><p>{m.text}</p></article>)}</div><form className="aop-composer" onSubmit={e => { e.preventDefault(); submitMessage() }}><label htmlFor="aop-message">{selectedRun ? "Message about this case" : "Message this agent"}</label><textarea id="aop-message" value={selectedRun ? agent.caseDrafts?.[selectedRun.id] ?? "" : agent.draft} onChange={e => setState(s => ({ ...s, agents: { ...s.agents, [agent.id]: { ...s.agents[agent.id], ...(selectedRun ? { caseDrafts: { ...s.agents[agent.id].caseDrafts, [selectedRun.id]: e.target.value } } : { draft: e.target.value }) } } }))} onKeyDown={e => { if (e.key === "Enter" && !e.shiftKey && !e.nativeEvent.isComposing) { e.preventDefault(); submitMessage() } }} maxLength={2000} rows={3} placeholder={selectedRun ? "Prioritize this case, pause it, or ask a question…" : "Ask for an update, pause intake, or hold notifications…"} /><div><small>Scripted demo · Enter to send</small><button type="submit" className="aop-send" aria-label="Send instruction" disabled={!(selectedRun ? agent.caseDrafts?.[selectedRun.id] ?? "" : agent.draft).trim()}><ArrowUp size={18} /></button></div></form></> : null}
    </dialog>
  </div>
}
