import { ArrowRight, CaretDown, Check, CheckCircle, Clock, FileText, Pause, Pulse, ShieldCheck, WarningCircle } from "@phosphor-icons/react"
import { useEffect, useState } from "react"
import { MaxionSpiralMark } from "@/features/platform-prototype/PortalChrome"
import { Button } from "./WorkspaceParts"
import { MAX_MOUNTED_RUNS, isTerminal, measures, needsAttention, phaseLabel, readiness, runActivity, workflowFor, type AgentAction, type Deployment, type OperationRole, type OperationRun, type RunAction } from "./operationsState"
import type { WorkflowId } from "./initiatives"

export function Status({ label, attention = false, active = false }: { label: string; attention?: boolean; active?: boolean }) {
  return <span className={`aop-status${attention ? " is-attention" : active ? " is-active" : ""}`}>{attention ? <WarningCircle size={14} /> : active ? <span className="aop-status-dot" /> : <Clock size={14} />}{label}</span>
}
export function AgentMark({ id }: { id: WorkflowId }) { return <span className="aop-agent-mark"><MaxionSpiralMark variant="current" /><span>{id === "service" ? "S" : id === "invoice" ? "F" : id === "inventory" ? "I" : "H"}</span></span> }

export function ReadinessPanel({ agent, onAction, onMapping }: { agent: Deployment; onAction: (action: AgentAction) => void; onMapping: (value: string) => void }) {
  const [editing, setEditing] = useState(false)
  const status = readiness(agent)
  return <section className="aop-readiness" aria-label="Deployment readiness"><div className="aop-section-title"><h2>Ready to operate?</h2><Status label={status === "ready" ? "Checks passed" : status === "checking" ? "Rechecking" : status === "unsupported" ? "Unsupported requirement" : "One setup fix"} active={status === "ready"} attention={status === "unsupported" || status === "repair"} /></div>
    <p>Agentix checks the required operations, your connection, field mappings and how each outcome will be verified.</p>
    {agent.automaticPayroll ? <div className="aop-repair" role="status"><div><WarningCircle size={20} /><div><h3>Automatic payroll provisioning isn’t supported.</h3><p>The integration has no certified provision-and-verify operation. A broader permission or field mapping won’t fix this.</p><small>Responsible: MAXION integrations · payroll obligation · checked in this demo</small></div></div><p className="aop-scope-delta">Available scope: the payroll owner provisions access; Agentix tracks their confirmation. This is a human-assisted process, not full automation.</p><Button primary onClick={() => onAction("use-human-payroll")}>Keep payroll with its owner</Button><button className="aop-text-button" disabled={agent.supportRequested} onClick={() => onAction("support")}>{agent.supportRequested ? "Demo request AGX-104 recorded · still unsupported" : "Request this capability from MAXION"}</button></div> : !agent.mapping ? <div className="aop-repair"><div><WarningCircle size={20} /><div><h3>Confirm the London access-package mapping.</h3><p>The location is known from Discovery. There are two catalog labels; confirm which approved package the IT request should use.</p><small>Responsible: People operations owner · only onboarding deployment is blocked</small></div></div>{editing ? <div className="aop-mapping"><label htmlFor="aop-mapping">London analyst → approved access package</label><select id="aop-mapping" value={agent.mapping} onChange={e => onMapping(e.target.value)}><option value="">Choose the approved package</option><option value="london-standard">UK · London analyst · standard access v4</option><option value="privileged" disabled>Privileged administrator · outside approved scope</option></select><small>No permissions are added. The chosen mapping will be checked before deployment.</small></div> : <Button primary onClick={() => setEditing(true)}>Confirm mapping<ArrowRight size={16} /></Button>}</div> : status === "checking" ? <p className="aop-checking" role="status"><Pulse size={18} />Validating mapping, operation coverage and read-back…</p> : !agent.checked ? <div className="aop-checking"><CheckCircle size={18} /><p>Mapping selected. Run the read-only readiness check before deployment.</p><Button primary onClick={() => onAction("recheck")}>Recheck readiness</Button></div> : <p className="aop-ready" role="status"><CheckCircle size={18} />Required operations are ready in this simulated environment. Payroll remains a named human obligation.</p>}
    <details className="aop-disclosure"><summary>Operation checks <CaretDown size={16} /></summary><ul className="aop-operation-checks"><li><Check size={16} /><span>Read approved hire and documents<small>Certified operation · scoped HR fields · source record read-back</small></span></li><li>{agent.mapping && agent.checked ? <Check size={16} /> : <WarningCircle size={16} />}<span>Reserve equipment and request standard access<small>{agent.mapping ? "Mapping selected · " : "Mapping unresolved · "}ServiceNow request and fulfillment verification</small></span></li><li><ShieldCheck size={16} /><span>Confirm payroll readiness<small>{agent.automaticPayroll ? "Automatic provision-and-verify unsupported" : "Human-owned · attestation and source evidence required"}</small></span></li></ul>{!agent.automaticPayroll ? <button className="aop-text-button" onClick={() => onAction("request-payroll")}>What if payroll must be fully automated?</button> : null}<small>Certification and connection readiness are simulated here. This is not a live provider certification.</small></details>
  </section>
}

export function RunsList({ runs, history, filter, onOpen }: { runs: OperationRun[]; history: boolean; filter: string; onOpen: (run: OperationRun) => void }) {
  const [limit, setLimit] = useState(20)
  useEffect(() => setLimit(20), [history, filter])
  const items = runs.filter(r => history ? isTerminal(r) : !isTerminal(r)).filter(r => filter !== "attention" || needsAttention(r)).sort((a, b) => history ? b.started - a.started : Number(needsAttention(b)) - Number(needsAttention(a)))
  const mounted = Math.min(limit, MAX_MOUNTED_RUNS)
  return <section aria-label={history ? "Execution history" : "Current work"} className="aop-work-list">{items.length ? items.slice(0, mounted).map(run => <button key={run.id} className="aop-run-row" onClick={() => onOpen(run)}><span className={`aop-run-icon${run.phase === "verified" ? " is-done" : ""}`}>{run.phase === "verified" ? <CheckCircle size={20} /> : needsAttention(run) ? <WarningCircle size={20} /> : <FileText size={20} />}</span><span className="aop-run-name"><strong>{run.reference}<span>{run.priority === "High" ? "High priority" : run.trigger}</span></strong><span>{run.title}</span><small>{history ? new Date(run.started).toLocaleString("en-GB", { timeZone: "UTC", dateStyle: "medium", timeStyle: "short" }) + " UTC" : runActivity(run)}</small></span><span className="aop-run-status"><Status label={phaseLabel(run.phase)} active={["working", "verifying", "recovering", "verified"].includes(run.phase)} attention={needsAttention(run) || run.phase === "not_completed"} /><ArrowRight size={16} /></span></button>) : <div className="aop-empty"><CheckCircle size={24} /><h3>{history ? "No completed cycles yet." : filter === "attention" ? "Nothing needs your decision." : "No open cases. The agent is watching."}</h3><p>{history ? "Each completed or unsuccessful attempt will appear here with its own outcome." : "New work arrives through the approved trigger. You don’t need to keep a conversation open."}</p></div>}{items.length > mounted && mounted < MAX_MOUNTED_RUNS ? <Button onClick={() => setLimit(n => Math.min(n + 20, MAX_MOUNTED_RUNS))}>Show 20 more cases</Button> : null}</section>
}
export function ValueSummary({ runs }: { runs: OperationRun[] }) {
  const m = measures(runs)
  return <section className="aop-value" aria-label="Outcome performance"><div className="aop-section-title"><h2>Outcomes, not activity counts</h2><span>Demo reporting period</span></div><div className="aop-metrics"><div><strong>{m.verified}<small> / {m.total}</small></strong><span>Verified outcomes</span></div><div><strong>{m.straightThrough}<small> / {m.eligible}</small></strong><span>Eligible cases completed autonomously</span></div><div><strong>{m.medianMinutes ?? "—"}<small> min</small></strong><span>Median verified cycle</span></div><div><strong>${m.cost.toFixed(2)}</strong><span>Simulated execution cost</span></div></div><details className="aop-disclosure"><summary>How this is calculated<CaretDown size={16} /></summary><p>Derived from the case records shown here, including failed and blocked attempts in total work and cost. Autonomous eligibility excludes required AP approvals and human payroll fulfillment. Cycle time uses verified cases only; open cases are not hidden from the total.</p><p>All figures are illustrative demo data, not production measurements. No agreed customer baseline is available, so no labor savings or ROI is claimed.</p></details></section>
}
export function RunDetail({ run, agent, role, onAction, onSteer }: { run: OperationRun; agent: Deployment; role: OperationRole; onAction: (action: RunAction, evidence?: string) => void; onSteer: () => void }) {
  const [reference, setReference] = useState(""); const [error, setError] = useState("")
  const workflow = workflowFor(run.agentId)
  const staleApproval = run.phase === "approval" && run.approvalVersion !== agent.version
  const stageDetails = [workflow.sources.map(source => source.title).join(" · "), workflow.team.map(member => `${member.name}: ${member.responsibility}`).join(" "), run.needsApproval ? `Approval is bound to ${run.reference} v2 and the $240 variance; never a payment authorization.` : run.agentId === "onboarding" ? "Payroll fulfillment remains assigned to its human owner; verification follows their reference." : "No additional human decision is required within this case’s approved scope.", workflow.boundary, `Read back ${run.reference} and retain the required notification acceptance receipt. An accepted send is not proof of receipt or reading.`]
  const checks = ["Required context and business rules checked", "Permitted record change applied", "Source read-back matches the intended result", "Required notification acceptance evidenced"]
  return <div className="aop-run-detail"><Status label={phaseLabel(run.phase)} active={run.phase === "verified"} attention={needsAttention(run)} /><h2>{run.title}</h2><p>{runActivity(run)}</p><section className="aop-case-contract"><h3>The business outcome</h3><p>{workflowFor(run.agentId).outcome}</p><small>{workflowFor(run.agentId).boundary}</small>{run.agentId === "service" ? <p>Incident remains open. This agent verifies routing and handoff, not incident resolution.</p> : null}</section>
    {staleApproval ? <section className="aop-decision" aria-label="Stale approval request"><h3>This approval belongs to deployment v{run.approvalVersion}.</h3><p>The agent now runs deployment v{agent.version}. Refresh the request before deciding; the amount and authority won’t change.</p><Button primary disabled={role !== "owner"} onClick={() => onAction("refresh-approval")}>Refresh approval request</Button>{role !== "owner" ? <small>A project owner must refresh this request.</small> : null}</section> : run.phase === "approval" ? <section className="aop-decision" aria-label="Approval request"><h3>Approve the $240 price variance?</h3><p>{run.reference} v{run.approvalVersion} · 120 units received. The price-only variance is outside automatic authority. Other cases continue.</p><small>No payment release or bank-detail changes.</small><div className="aop-actions"><Button primary disabled={role !== "owner"} onClick={() => onAction("approve")}>Approve $240 variance</Button><Button disabled={role !== "owner"} onClick={() => onAction("decline")}>Decline</Button></div>{role !== "owner" ? <small>A project owner must resolve this decision.</small> : null}</section> : null}
    {run.phase === "human" ? <section className="aop-decision" aria-label="Human fulfillment"><h3>Payroll owner confirmation needed</h3><p>HR and IT work is preserved. The payroll owner must provide fulfillment evidence; the agent cannot grant itself access.</p><label htmlFor="aop-fulfillment">Fulfillment reference</label><input id="aop-fulfillment" value={reference} disabled={role === "viewer"} onChange={e => setReference(e.target.value)} maxLength={120} placeholder="For example, PAYROLL-306" aria-invalid={!!error} /><Button primary disabled={role === "viewer"} onClick={() => { if (!reference.trim()) setError("Enter the owner’s fulfillment reference."); else { setError(""); onAction("fulfill", reference) } }}>Attach owner confirmation</Button>{error ? <p role="alert">{error}</p> : null}<small>Owner: payroll administrator · due before the hire’s start date. Demo attestation; not independent provider proof.</small></section> : null}
    {run.phase === "partial" ? <section className="aop-decision" aria-label="Partial outcome"><h3>Change applied. Notification is still outstanding.</h3><p>{agent.connection === "expired" ? "The notification connection expired. Repair it from the agent’s status banner; completed writes will not be repeated." : "A notification hold is in effect. The original outcome remains incomplete until the required notification is verified."}</p>{agent.connection === "ready" && !agent.holdNotifications ? <Button primary onClick={() => onAction("release")}>Release this notification</Button> : null}</section> : null}
    <section className="aop-checklist" aria-label="Case outcome checks"><h3>{run.phase === "verified" ? "Verified outcome" : "What counts as complete"}</h3>{checks.map((check, i) => { const done = run.phase === "verified" || i === 0 && run.step >= 2 || i === 1 && run.writes === 1; return <div key={check}>{done ? <CheckCircle size={18} /> : <span className="aop-empty-check" />}<span>{check}</span></div> })}{run.phase === "verified" ? <p>Completed for {run.reference} only. The agent stays deployed for new work.</p> : null}</section>
    <details className="aop-disclosure"><summary>Activity & evidence<CaretDown size={16} /></summary><p>Outcome contract · {run.reference} · deployment v{agent.version} · {run.trigger.toLowerCase()} {run.occurrence}</p><ol>{["Read and validate authorized context", "Reconcile required evidence", "Resolve material decision, if required", "Apply the authorized change", "Verify source result and required notification"].map((text, i) => <li key={text}><details className="aop-activity-step"><summary><span>{i + 1}. {text}</span><small>{run.phase === "verified" || i < run.step ? "Recorded" : run.phase === "not_completed" ? "Not completed" : i === run.step ? "Current" : "Pending"}</small></summary><p>{stageDetails[i]}</p><small>{run.phase === "verified" || i < run.step ? `Simulated case evidence · ${run.reference} · stage ${i + 1}` : "Planned or in progress; no completion receipt claimed."}</small></details></li>)}</ol><p>Record writes: {run.writes} · Duplicate writes: 0{run.recovered ? " · original submission reconciled" : ""}</p>{run.humanReference ? <p>Human attestation: {run.humanReference}</p> : null}{run.notes.map((note, i) => <p key={i}>{note}</p>)}<small>All effects and receipts are simulated. Provider acceptance is not recipient delivery or acknowledgement.</small></details>
    <div className="aop-actions"><Button disabled={role === "viewer"} onClick={onSteer}>Message about this case</Button>{!isTerminal(run) && ["working", "queued", "verifying", "recovering", "paused"].includes(run.phase) ? <Button disabled={role === "viewer"} onClick={() => onAction(run.phase === "paused" ? "resume" : "pause")}><Pause size={16} />{run.phase === "paused" ? "Resume case" : "Pause case"}</Button> : null}</div>
  </div>
}
