import { ArrowRight, CaretDown, Check, CheckCircle, Clock, FileText, Pulse, ShieldCheck, WarningCircle } from "@phosphor-icons/react"
import { useEffect, useState } from "react"
import { MaxionSpiralMark } from "@/features/platform-prototype/PortalChrome"
import { Button } from "./WorkspaceParts"
import { MAX_MOUNTED_RUNS, isTerminal, measures, needsAttention, phaseLabel, readiness, runActivity, type AgentAction, type Deployment, type OperationRun } from "./operationsState"
import type { WorkflowId } from "./initiatives"

export function Status({ label, attention = false, active = false }: { label: string; attention?: boolean; active?: boolean }) {
  return <span className={`aop-status${attention ? " is-attention" : active ? " is-active" : ""}`}>{attention ? <WarningCircle size={14} /> : active ? <span className="aop-status-dot" /> : <Clock size={14} />}{label}</span>
}
export function AgentMark({ id }: { id: WorkflowId }) { return <span className="aop-agent-mark"><MaxionSpiralMark variant="current" /><span>{id === "service" ? "S" : id === "invoice" ? "F" : id === "inventory" ? "I" : "H"}</span></span> }

export function ReadinessPanel({ agent, onAction, onMapping }: { agent: Deployment; onAction: (action: AgentAction) => void; onMapping: (value: string) => void }) {
  const [editing, setEditing] = useState(false)
  const status = readiness(agent)
  return <section className="aop-readiness" aria-label="Deployment readiness"><div className="aop-section-title"><h2>Ready to operate?</h2><Status label={status === "ready" ? "Checks passed" : status === "checking" ? "Rechecking" : status === "unsupported" ? "Unsupported requirement" : "One setup fix"} active={status === "ready"} attention={status === "unsupported" || status === "repair"} /></div>
    <p>Agentix checks the required operations, your connection, field mappings and how each outcome will be verified.</p>
    {agent.automaticPayroll ? <div className="aop-repair" role="status"><div><WarningCircle size={20} /><div><h3>Automatic payroll provisioning isn’t supported.</h3><p>The integration has no certified provision-and-verify operation. A broader permission or field mapping won’t fix this.</p><small>Responsible: MAXION integrations · payroll obligation · checked in this demo</small></div></div><p className="aop-scope-delta">Available scope: the payroll owner provisions access; Agentix tracks their confirmation. This is a human-assisted process, not full automation.</p><Button primary onClick={() => onAction("use-human-payroll")}>Keep payroll with its owner</Button><button className="aop-text-button" disabled={agent.supportRequested} onClick={() => onAction("support")}>{agent.supportRequested ? "Demo request AGX-104 recorded · still unsupported" : "Request this capability from MAXION"}</button></div> : !agent.mapping ? <div className="aop-repair"><div><WarningCircle size={20} /><div><h3>Confirm the London access-package mapping.</h3><p>The location is known from Discovery. There are two catalog labels; confirm which approved package the IT request should use.</p><small>Responsible: People operations owner · only onboarding deployment is blocked</small></div></div>{editing ? <div className="aop-mapping"><label htmlFor="aop-mapping">London analyst → approved access package</label><select id="aop-mapping" value={agent.mapping} onChange={e => onMapping(e.target.value)}><option value="">Choose the approved package</option><option value="london-standard">UK · London analyst · standard access v4</option><option value="privileged" disabled>Privileged administrator · outside approved scope</option></select><small>No permissions are added. The chosen mapping will be checked before deployment.</small></div> : <Button primary onClick={() => setEditing(true)}>Confirm mapping<ArrowRight size={16} /></Button>}</div> : status === "checking" ? <p className="aop-checking" role="status"><Pulse size={18} />Validating mapping, operation coverage and read-back…</p> : !agent.checked ? <div className="aop-checking"><CheckCircle size={18} /><p>Mapping selected. Run the read-only readiness check before deployment.</p><Button primary onClick={() => onAction("recheck")}>Recheck readiness</Button></div> : <p className="aop-ready" role="status"><CheckCircle size={18} />Required operations are ready in this simulated environment. Payroll remains a named human obligation.</p>}
    <details className="aop-disclosure"><summary>Operation checks <CaretDown size={16} /></summary><ul className="aop-operation-checks"><li><Check size={16} /><span>Read approved hire and documents<small>Certified operation · scoped HR fields · source record read-back</small></span></li><li>{agent.mapping && agent.checked ? <Check size={16} /> : <WarningCircle size={16} />}<span>Reserve equipment and request standard access<small>{agent.mapping ? "Mapping selected · " : "Mapping unresolved · "}ServiceNow request and fulfillment verification</small></span></li><li><ShieldCheck size={16} /><span>Confirm payroll readiness<small>{agent.automaticPayroll ? "Automatic provision-and-verify unsupported" : "Human-owned · attestation and source evidence required"}</small></span></li></ul>{!agent.automaticPayroll ? <button className="aop-text-button" onClick={() => onAction("request-payroll")}>What if payroll must be fully automated?</button> : null}<small>Certification and connection readiness are simulated here. This is not a live provider certification.</small></details>
  </section>
}

export function RunsList({ runs, history, filter, onOpen }: { runs: OperationRun[]; history: boolean; filter: string; onOpen: (run: OperationRun) => void }) {
  const [limit, setLimit] = useState(20)
  useEffect(() => setLimit(20), [history, filter])
  const items = runs.filter(r => history ? isTerminal(r) : !isTerminal(r)).filter(r => filter !== "attention" || needsAttention(r)).sort((a, b) => history ? b.started - a.started : Number(needsAttention(b)) - Number(needsAttention(a)))
  const mounted = Math.min(limit, MAX_MOUNTED_RUNS)
  return <section aria-label={history ? "Execution history" : "Current work"} className="aop-work-list">{items.length ? items.slice(0, mounted).map(run => <button key={run.id} className="aop-run-row" onClick={() => onOpen(run)}><span className={`aop-run-icon${run.phase === "verified" ? " is-done" : ""}`}>{run.phase === "verified" ? <CheckCircle size={20} /> : needsAttention(run) ? <WarningCircle size={20} /> : <FileText size={20} />}</span><span className="aop-run-name"><strong>{run.reference}<span>{run.priority === "High" ? "High priority" : run.trigger}</span></strong><span>{run.title}</span><small>{history ? new Date(run.started).toLocaleString("en-GB", { timeZone: "UTC", dateStyle: "medium", timeStyle: "short" }) + " UTC" : runActivity(run)}</small></span><span className="aop-run-status"><Status label={phaseLabel(run.phase)} active={["working", "verifying", "recovering", "verified"].includes(run.phase)} attention={needsAttention(run) || run.phase === "not_completed"} /><ArrowRight size={16} /></span></button>) : <div className="aop-empty"><CheckCircle size={24} /><h3>{history ? "No completed cycles yet." : filter === "attention" ? "Nothing needs your decision." : "No open cases. The agent is watching."}</h3><p>{history ? "Each completed or unsuccessful attempt will appear here with its own outcome." : "New work arrives through the approved trigger. You don’t need to keep a conversation open."}</p></div>}{items.length > mounted && mounted < MAX_MOUNTED_RUNS ? <Button onClick={() => setLimit(n => Math.min(n + 20, MAX_MOUNTED_RUNS))}>Show 20 more cases</Button> : null}</section>
}
export function ValueSummary({ runs }: { runs: OperationRun[] }) {
  const m = measures(runs)
  return <section className="aop-value" aria-label="Outcome performance"><div className="aop-section-title"><h2>Outcomes, not activity counts</h2><span>Demo reporting period</span></div><div className="aop-metrics"><div><strong>{m.verified}<small> / {m.total}</small></strong><span>Verified outcomes</span></div><div><strong>{m.straightThrough}<small> / {m.eligible}</small></strong><span>Eligible cases completed autonomously</span></div><div><strong>{m.medianMinutes ?? "—"}<small> min</small></strong><span>Median verified cycle</span></div><div><strong>${m.cost.toFixed(2)}</strong><span>Simulated execution cost</span></div></div><details className="aop-disclosure"><summary>How this is calculated<CaretDown size={16} /></summary><p>Derived from the case records shown here, including failed and blocked attempts in total work and cost. Autonomous eligibility excludes required AP approvals and human payroll fulfillment. Cycle time uses verified cases only; open cases are not hidden from the total.</p><p>All figures are illustrative demo data, not production measurements. No agreed customer baseline is available, so no labor savings or ROI is claimed.</p></details></section>
}
